package LoginPages;
import AdminClasses.AdministrationMenu;
import AdvisorClasses.AdvisorMenu;
import AdvisorClasses.LatePayment;

import javax.mail.MessagingException;
import javax.swing.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gordo
 */
public class AdvisorLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */

    private Random random;
    private int secretCode;
    private TwoFactorAuthentication twoFactorAuthentication;

    public AdvisorLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        myPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameBox = new javax.swing.JTextField();
        passwordBox = new javax.swing.JPasswordField();
        sixDigitBox = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        sendCode = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Travel Advisor login");
        setPreferredSize(new java.awt.Dimension(900, 357));
        setResizable(false);
        pack();
        setLocationRelativeTo(null);

        myPanel.setBackground(new java.awt.Color(153, 204, 255));
        myPanel.setPreferredSize(new java.awt.Dimension(900, 357));

        jLabel6.setIcon(new javax.swing.ImageIcon("data/AirViaLogo.png")); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Login as Travel Advisor");

        usernameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameBoxActionPerformed(evt);
            }
        });

        sixDigitBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixDigitBoxActionPerformed(evt);
            }
        });

        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    loginButtonActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Staff ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("6 digit code");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        jLabel7.setIcon(new javax.swing.ImageIcon("data/advisor.png")); // NOI18N

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        sendCode.setText("SEND CODE");
        sendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    sendCodeActionPerformed(evt);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("data/uniJetLogo.png")); // NOI18N

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
                myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(myPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addGap(34, 34, 34))
                        .addGroup(myPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2)
                                                                .addComponent(jLabel5)))
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(usernameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(passwordBox)
                                                                                .addGroup(myPanelLayout.createSequentialGroup()
                                                                                        .addComponent(sixDigitBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(sendCode)))))
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel1)
                                                .addGap(21, 21, 21)))
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel7)
                                                .addContainerGap(79, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(90, 90, 90))))
        );
        myPanelLayout.setVerticalGroup(
                myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(myPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(backButton)
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, myPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addContainerGap())
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel7)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel8)
                                                                .addGap(70, 70, 70))
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(usernameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(passwordBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5))
                                                                .addGap(9, 9, 9)
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(sixDigitBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(sendCode))
                                                                .addGap(20, 20, 20)
                                                                .addComponent(loginButton)
                                                                .addGap(104, 104, 104))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(myPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void usernameBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void sixDigitBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * Generates a random number which will be emailed to the Travel Advisor for two-factor authentication
     */
    private void generateRandomNumber(){
        random = new Random();
        secretCode = random.nextInt(900000) + 100000;
    }

    /**
     * Sends the generated code to the Travel Advisor's email when the sendCode button is pressed
     */
    private void sendCodeActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        //Checking if the username and the password is filled in.
        if(usernameBox.getText().length() == 0 || passwordBox.getPassword().length == 0){
            int option = JOptionPane.showOptionDialog(null, "Please Enter Credentials", "Login", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[]{"OK"}, "OK");

        }
        else {
            // Storing the data entered by the user from the username and password boxes

            String idStr = usernameBox.getText();
            int id = Integer.valueOf(idStr);
            String pwd = String.valueOf(passwordBox.getPassword());

            SQLLoginHelper l = new SQLLoginHelper(); // new SQLHelper instance

            if (l.attemptLogin("Travel Advisor", id, pwd)) {
                generateRandomNumber();
                try {
                    twoFactorAuthentication.Send2FAEmail(l.getEmail(), Integer.toString(secretCode));
                } catch (IOException e) {
                    throw new RuntimeException(e);
                } catch (MessagingException e) {
                    throw new RuntimeException(e);
                }
                //new AdministrationMenu(l.getStaffID(),l.getName()).setVisible(true); // if the login is successful, the admin dashboard successfully opens#

            } else {
                // if details are incorrect, an info box will pop up and show that the user may try again
                JOptionPane.showMessageDialog(null, "Incorrect username or password, please try again");
            }
        }
    }

    /**
     * Allows login into the system when the Advisor presses the login button and makes sure credentials match
     */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {

        //Checking if the username and the password is filled in.
        if(usernameBox.getText().length() == 0 || passwordBox.getPassword().length == 0 ||sixDigitBox.getText().length() == 0 ){
            int option = JOptionPane.showOptionDialog(null, "Please Enter Credentials", "Login", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, new String[]{"OK"}, "OK");

        }
        else {

            // Storing the data entered by the user from the username and password boxes

            String idStr = usernameBox.getText();
            int id = Integer.valueOf(idStr);
            String pwd = String.valueOf(passwordBox.getPassword());


            SQLLoginHelper l = new SQLLoginHelper(); // new SQLHelper instance
            l.attemptLogin("Travel Advisor", id, pwd);
            System.out.println(sixDigitBox.getText());
            System.out.println(Integer.toString(secretCode));
            if ( sixDigitBox.getText().compareTo(Integer.toString(secretCode)) == 0) {
                new AdvisorMenu(l.getStaffID(), l.getName()).setVisible(true); // if the login is successful, the admin dashboard successfully opens
                LatePayment late = new LatePayment();
                late.latePaymentAlert(id);
                JOptionPane.showMessageDialog(null, "LATE PAYMENT ALERT The following customers can pay within 30 days: " + late.getCustomers());
                dispose();
            } else {
                // if details are incorrect, an info box will pop up and show that the user may try again
                JOptionPane.showMessageDialog(null, "Incorrect Pin");
            }
        }
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
        new StartPage().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvisorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvisorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvisorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvisorLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvisorLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel myPanel;
    private javax.swing.JPasswordField passwordBox;
    private javax.swing.JButton sendCode;
    private javax.swing.JTextField sixDigitBox;
    private javax.swing.JTextField usernameBox;
    // End of variables declaration
}
